name: CI

# Run this workflow every time a commit gets pushed to main or a pull request gets opened against main
on:
  push:
    branches:
      - master

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: juliakm/pipelines@master
          with:
            azure-devops-project-url: https://dev.azure.com/jukullam/learning
            azure-pipeline-name: 'juliakm.pipelines-dotnet-core (1)'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
